### ISSUE TITLE
resolve paths

### ISSUE THREAD

**Issue by bennypowers** [a7ul/esbuild-node-tsc#11]
It would be cool if this resolved typescript paths.

see also #4

**Comment by a7ul** [comment]
Could you explain what you mean by typescript paths ?

**Comment by PabloSzx** [comment]
> Could you explain what you mean by typescript paths ?

https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

**Comment by bennypowers** [comment]
Say you had this tsconfig.json
```json
{
  "include": ["graphql", "../lib"],
  "exclude": ["node_modules"],
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2019",
    "outDir": "./dist",
    "baseUrl": "./",
    "rootDir": "../",
    "importHelpers": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "strict": false,
    "inlineSourceMap": true,
    "plugins": [{ "transform": "@zerollup/ts-transform-paths" }],
    "paths": {
      "#entities/*": ["graphql/entities/*"],
      "#test/*": ["graphql/test/*"],
      "#lib/*": ["../lib/*"],
      "#schema": ["graphql/generated/graphql"],
      "graphql": ["node_modules/graphql"],
      "graphql/*": ["node_modules/graphql/*"],
    }
  }
}
```
and this typescript:
```ts
import { add } from '#lib/math';

export default add(1, 1);
```

**Comment by skoshy** [comment]
Trying to use this with just `baseUrl` set to `./`, but I get `Cannot find module` errors. Would be great to have this be supported.

**Comment by nicoburns** [comment]
Looks like this could be implemented using ESBuild's resolve callbacks (https://esbuild.github.io/plugins/#resolve-callbacks). Although there would need to be some translation layer from TypeScript paths syntax to ESBuild's regex-based resolve plugins.

**Comment by KubaJastrz** [comment]
I found this plugin, it still looks like it's being developed, but seems to work https://www.npmjs.com/package/@esbuild-plugins/tsconfig-paths

**Comment by joeyfigaro** [comment]
@KubaJastrz Not working here, unfortunately.
