### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by bishwenduk029** [a7ul/esbuild-node-tsc#13]
I tried compiling my typescript project with etsc but when running with node on command line I am encountering this error ```ReferenceError: require is not defined```
My tsconfig.json is 
```
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "sourceMap": false,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "noUnusedLocals": false,
    "moduleResolution": "node"
  },
  "exclude": ["node_modules", "dist"]
}
```

Any help on this from anyone would be great. Thanks in advance.

**Comment by dahukish** [comment]
This seems similar to this thread: https://github.com/evanw/esbuild/issues/506
Looking to see if this might work for me: https://github.com/evanw/esbuild/issues/451
