### ISSUE TITLE
How transform to esm?

### ISSUE THREAD

**Issue by 1018715564** [a7ul/esbuild-node-tsc#33]
```
const esbuildPluginTsc = require('esbuild-plugin-tsc');

module.exports = {
  outDir: './dist',
  esbuild: {
    minify: false,
    format: "esm",
    target: 'es2015',
    plugins: [esbuildPluginTsc()]
  },
  assets: {
    baseDir: 'src',
    outDir: './dist',
    filePatterns: ['**/*.json']
  }
};

```

**Comment by desko27** [comment]
Seems like format is hardcoded to `cjs` and, since the spread operator comes first, format value cannot be overridden by an option:

https://github.com/a7ul/esbuild-node-tsc/blob/81f32d98b332d3d4b0e93516c3e200d650e17944/src/index.ts#L87-L94

**Comment by 1018715564** [comment]
ohhhh all right

**Comment by a7ul** [comment]
could you raise a pr for this ?

**Comment by 1018715564** [comment]
ok, look like so easy

**Comment by 1018715564** [comment]
this is pr: https://github.com/a7ul/esbuild-node-tsc/pull/36

**Comment by desko27** [comment]
Not sure #36 alone solves the issue, please @1018715564 let us know

**Comment by 1018715564** [comment]
sorry, Due to my negligence, I forgot to add the format option to config
this is pr: https://github.com/a7ul/esbuild-node-tsc/pull/38

I have tested it and can package the code in esm format normally

![image](https://user-images.githubusercontent.com/35763284/143158565-0fe37fe4-e0a7-4dc9-89bf-8158337da81b.png)
