### ISSUE TITLE
Using rimraf is dangerous.

### ISSUE THREAD

**Issue by LumaKernel** [a7ul/esbuild-node-tsc#35]
`tsc` allows to output next to the input file, so I tried that with this... and you can imagine what occurs. Fortunately it was not so big problem, but I scared. 
I think this should only put but avoid rimraf-ing.

**Comment by srich-kr** [comment]
I've had the same problem. We put output files next to input files. Rimraf-ing just deletes everything.

**Comment by a7ul** [comment]
This is now resolved in v1.8.4

rimraf only runs if you specify `clean: true` in the config.
