### ISSUE TITLE
'etsc' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by thousandsofraccoons** [a7ul/esbuild-node-tsc#39]
Hello, thank you for a nice library, after migration from npm to pnpm I got the following error:
`'etsc' is not recognized as an internal or external command, operable program or batch file.`

How can I fix it?

**Comment by a7ul** [comment]
Havent used pnpm but you could maybe try 
```
pnpm exec etsc
```

or `pnpm etsc` ?

`etsc` is just a binary in `node_modules/.bin`
