### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by will0923** [a7ul/esbuild-node-tsc#45]
**tsconfig.json:**
{
    "compilerOptions": {
        ...
        "paths": {
            "@/*": ["./src/*"],
        }
    },
}

**ests.config.js:**
const tsPaths = require("esbuild-ts-paths");
module.exports = {
    esbuild: {
        plugins: [tsPaths()],
    },
};

Error: Cannot find module '@/xxxx/xxxx'

**Comment by a7ul** [comment]
This is now fixed in v2.0
https://github.com/a7ul/esbuild-node-tsc/tree/v2.0.0#v20-migration-and-breaking-changes- 
All esbuild options are passed now
