### ISSUE TITLE
used to include graphql schema files on dist folder but its not workng anymore any fixes?

### ISSUE THREAD

**Issue by sumit-yadav1** [a7ul/esbuild-node-tsc#48]

**Comment by a7ul** [comment]
which version are you using?

**Comment by sumit-yadav1** [comment]
> which version are you using?

using  v1.8.6

**Comment by sumit-yadav1** [comment]
> > which version are you using?
> 
> using v1.8.6

I tried updating to latest version but have same issue please help It started happening suddenly

**Comment by a7ul** [comment]
Makes sense. Could you try v1.8.5  and let me know if that works?

**Comment by sumit-yadav1** [comment]
> Makes sense. Could you try v1.8.5 and let me know if that works?
:( no its not working I tried v1.8.5 and v1.8.5
this is my nodemon.json file
{
  "watch": ["src"],
  "ignore": ["src/**/*.test.ts"],
  "ext": "ts,mjs,js,json,graphql",
  "exec": "etsc && node ./dist/server.js",
  "legacyWatch": true
}

**Comment by a7ul** [comment]
This should be fixed now in v2.0
https://github.com/a7ul/esbuild-node-tsc/tree/v2.0.0#v20-migration-and-breaking-changes-
