### ISSUE TITLE
ERR_REQUIRE_ESM, tries to require a true ESM module

### ISSUE THREAD

**Issue by brandonculverwork** [a7ul/esbuild-node-tsc#51]
It seems to be trying to require a native ESM module with the default settings.

https://github.com/sindresorhus/file-type is the library in question.

**Comment by a7ul** [comment]
Think its because the project itself is in esm and needs the project using it also be in esm

The readme of the said project says

This package is a ESM package. Your project needs to be ESM too. Read more.
