### ISSUE TITLE
Specify a different `tsconfig.json` file

### ISSUE THREAD

**Issue by lncramer** [a7ul/esbuild-node-tsc#58]
I have a need to use a different `tsconfig.json` file with `etsc`.

`esbuild` supports passing a different file with the `tsconfig` option (https://esbuild.github.io/api/#tsconfig), so would it be possible to add it here as well? Thanks!

**Comment by a7ul** [comment]
Yep, you can specify these values in the config

<img width="461" alt="image" src="https://user-images.githubusercontent.com/4029423/216163274-d0496559-cc32-4037-b111-58a5ae9d09cb.png">

**Comment by lncramer** [comment]
Amazing, thank you! Closing the issue.
