### ISSUE TITLE
Compile errors due to `.d.ts` files

### ISSUE THREAD

**Issue by felipe-augusto** [a7ul/esbuild-node-tsc#8]
Compiling fails when trying to transpile `.d.ts` files, I figure that I had to add the below lines to my `tsconfig.json`:

```ts
"exclude": [
    "**/*.test.ts",
    "**/*.d.ts"
 ]
```

The problem is that I don't want to add that to my main `tsconfig.json` because that is used in production, so I created another `tsconfig.dev.json` and patched your code to support a custom `tsconfig` file:

```ts
yarn etsc tsconfig.dev.json
```

I had to patch this line:

```ts
const tsConfigFile = findConfigFile(cwd, sys.fileExists, process.argv[2] || "tsconfig.json");
```

Do you think it makes sense for you guys do add this option? Maybe there is another way around to fix `.d.ts` files?

**Comment by RIP21** [comment]
+1 pretty annoying :) Have the same situation.

**Comment by a7ul** [comment]
This was solved in https://github.com/a7ul/esbuild-node-tsc/pull/14 by @Akumzy

**Comment by RIP21** [comment]
@a7ul awesome. Thanks for the great tool! :)
