### ISSUE TITLE
inlineSourceMap is mutually exclusive with sourceMap

### ISSUE THREAD

**Issue by jakeklassen** [a7ul/esbuild-node-tsc#9]
When using this package with `inlineSourceMap: true` it will not generate source maps due to:

```typescript
function esBuildSourceMapOptions(tsConfig: TSConfig) {
  if (!tsConfig.options.sourceMap) { // <----
    return false;
  }
  return tsConfig.options.inlineSourceMap ? "inline" : "external";
}
```

requiring `sourceMap` to be true. If you do this you'll get complaints in vscode that these two are mutally exclusive.

See https://www.typescriptlang.org/tsconfig#inlineSourceMap for reference.

It still _works_ if you set both fields, but you'll get error feedback in vscode on the `tsconfig.json` file.

**Comment by a7ul** [comment]
Makes sense. Could you raise a pr with a fix ?
